### ISSUE TITLE
Usage?

### ISSUE THREAD

**Issue by kalligator** [orenhavshush/cmb2-post-format-show_on-filter#1]
Can you provide an example usage syntax?

**Comment by PTiCA1** [comment]
Yes, exactly what I needed.
thank you

**Comment by SogoDigital** [comment]
Hi, 
you will need to use the "show_on" parameter

$cmb = new_cmb2_box( array(
        'id'            => 'test_metabox',
        'title'         => __('Article video', 'sage'),
        'object_types'  => array( 'post', ), // Post type
        'context'       => 'normal',
        'priority'      => 'high',
       'show_on'       => array( 'key' => 'post_format', 'value' => 'video' ),
        'show_names'    => true, // Show field names on the left

```
) );
```

**Comment by kalligator** [comment]
Thanks, it's working at last! 
I proposed this to be included in the readme

**Comment by SogoDigital** [comment]
thx will do

2015-08-13 12:06 GMT+03:00 kalligator notifications@github.com:

> Thanks, it's working at last!
> I proposed this to be included in the readme
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/orenhavshush/cmb2-post-format-show_on-filter/issues/1#issuecomment-130586207
> .

## 

Oren Havshush

M: 050-5506525  |   Office: 09-7719393
