### ISSUE TITLE
Only showing when post is saved

### ISSUE THREAD

**Issue by jakebresnehan** [orenhavshush/cmb2-post-format-show_on-filter#3]
Hey @orenhavshush!

Top work on the filter. Just one quick question. 

The `show_on` filter is only being shown once I have **saved** the post. Not dynamically on change of the radio buttons.

Is this the way it works for you?

`e.g. 'show_on'      => array( 'key' => 'post_format', 'value' => 'video' ),`
Only shows once the post format has been changed to video and the post is **saved**.

**Comment by PTiCA1** [comment]
good question

**Comment by SogoDigital** [comment]
Yes this is only after saving the post

**Comment by jakebresnehan** [comment]
No worries. Just thought I would double check. 

Thanks for the quick reply!

**Comment by PTiCA1** [comment]
Or use javascript to show / hide
[hide-meta-box-based-on-post-format](http://wordpress.stackexchange.com/questions/83382/hide-meta-box-based-on-post-format)

**Comment by SogoDigital** [comment]
You cannot as the decision to print the metabox is done on the server and not the client
if you want to use javascript to show\hide - you dont need this filter and yu can use only the js solution
