### ISSUE TITLE
Displays on new posts

### ISSUE THREAD

**Issue by grwgreg** [orenhavshush/cmb2-post-format-show_on-filter#4]
The metabox shows up on the new post edit page before being saved regardless of whether the correct format type is checked off. After being saved, the filter works properly.

Is there any way to check if a post is new from within the cmb_show_on_post_format function?

Thanks

**Comment by SogoDigital** [comment]
as I see it, it should be display only if it match the post format, I checked it and it is working

**Comment by grwgreg** [comment]
Thanks for the reply. On my end the problem was I had multiple metaboxes for different post format types. But when creating a new post, before the post is saved, all the metaboxes would show. I can see why this behavior might be preferred but I was able to hide it before being saved by changing this segment of code,

if ( ! $post_id ) {
  //return $display;
  return false;
}

This fixed it in my case.

**Comment by anybany** [comment]
Hi @grwgreg 
Do you think it is possible to show/hide the metaboxes when switching the post format **on an unsaved post?**

**Comment by SogoDigital** [comment]
Yes you can do it in JS, you should print all of them and hide/ show in js

**Comment by anybany** [comment]
i found some js for that but i cant get it to work properly.
could you please have a look at it?

```
    jQuery( document ).ready( function($)
    {
        $( "#ath_partner1" ).addClass( "hidden" );

        if( $( "input#post-format-link" ).is(":checked") ){
            $( "#ath_partner1" ).removeClass( "hidden" );
        }

        $( "input#post-format-link" ).change( function() {
            if( $(this).is(":checked") ){
                $( "#ath_partner1" ).removeClass( "hidden" );
            }
        } );

        }
     );
```

When i create a new post the metabox #ath_partner1 is hidden and when i switch to post format link it is displayed. so far so good. but when i change the post format again it doesn't get hide again.

It's the same on existing posts with post format link. When i change the post format the metabox stays visible.

**Comment by SogoDigital** [comment]
did you check for js error ? can you share a link and I will check it
